// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd7Rk1w9H5lwFXGHo-iN6y-z3ik9bdnMA',
    appId: '1:43960178016:web:23f7fca75c5271ff503a05',
    messagingSenderId: '43960178016',
    projectId: 'dhia-fou',
    authDomain: 'dhia-fou.firebaseapp.com',
    storageBucket: 'dhia-fou.appspot.com',
    measurementId: 'G-2Z12KPB10R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-gwUFtBpegzcxJDtlZNl1fOm-kDnTAoc',
    appId: '1:43960178016:android:11cbfb0bd483674f503a05',
    messagingSenderId: '43960178016',
    projectId: 'dhia-fou',
    storageBucket: 'dhia-fou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcgPN1xS8DCkPAy0-lJ5xIbTBrcCV4t_U',
    appId: '1:43960178016:ios:44af88a140217fa7503a05',
    messagingSenderId: '43960178016',
    projectId: 'dhia-fou',
    storageBucket: 'dhia-fou.appspot.com',
    iosClientId: '43960178016-s0e0shitgr2683br9jj5fa6gc6scbuql.apps.googleusercontent.com',
    iosBundleId: 'com.example.efim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcgPN1xS8DCkPAy0-lJ5xIbTBrcCV4t_U',
    appId: '1:43960178016:ios:d96bf0e735864b17503a05',
    messagingSenderId: '43960178016',
    projectId: 'dhia-fou',
    storageBucket: 'dhia-fou.appspot.com',
    iosClientId: '43960178016-vt00t6bp4cgqbssol26igr61fbvfp0tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.efim.RunnerTests',
  );
}
